### ISSUE TITLE
Getting issue running last version

### ISSUE THREAD

**Issue by moshemalawach** [Galexrt/docker-taiga#2] opened 2018-09-10 08:44 UTC
taigaio_1        |   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
taigaio_1        |     return getattr(connections[DEFAULT_DB_ALIAS], item)
taigaio_1        |   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/utils.py", line 211, in __getitem__
taigaio_1        |     backend = load_backend(db['ENGINE'])
taigaio_1        |   File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/utils.py", line 134, in load_backend
taigaio_1        |     raise ImproperlyConfigured(error_msg)
taigaio_1        | django.core.exceptions.ImproperlyConfigured: 'transaction_hooks.backends.postgresql_psycopg2' isn't an available database backend.
taigaio_1        | Try using 'django.db.backends.XXX', where XXX is one of:
taigaio_1        |     'mysql', 'oracle', 'postgresql', 'sqlite3'
taigaio_1        | Error was: No module named 'transaction_hooks'

**Comment by galexrt** [comment] 2018-09-10 08:46
Closing as duplicate of #1.

**Closed as completed by galexrt** 2018-09-10 08:46 UTC
